spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?serverTimezone=Asia/Seoul
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create
        hbm2ddl:
          auto: create
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

external-server:
  metadata:
    url: https://api.odcloud.kr/api
